# Regressão Linear Multipla 

In [ ]:
Variável o que significa: 
    
X1. Taxa de criminalidade per capita por cidade
X2. Proporção de terrenos residenciais zoneados para lotes com mais de 25.000 pés quadrados.
X3. Proporção de acres de negócios não varejistas por cidade
X4. Variável dummy de Charles River (= 1 se a área delimita o rio; 0 caso contrário)
X5. Concentração de óxidos nítricos (partes por 10 milhões)
X6. Número médio de quartos por habitação
X7. Proporção de unidades ocupadas pelo proprietário construídas antes de 1940
X8. Distâncias ponderadas para cinco centros de emprego de Boston
X9. Índice de acessibilidade às rodovias radiais
X10. Taxa de imposto de propriedade de valor total por $ 10.000
X11. Proporção aluno-professor por cidade
X12. B: 1000 (Bk - 0,63) ^ 2, onde Bk é a proporção de negros por cidade
X13. % status inferior da população
Y.  Valor médio de casas ocupadas pelo proprietário em $ 1000

In [1]:
import numpy as np
import statsmodels.api as sm

In [7]:
#Variavel resposta y
y = [24,21.6,34.7,33.4,36.2,28.7,22.9,27.1,16.5,18.9,15,18.9,21.7,20.4,18.2,19.9,23.1,17.5,20.2,18.2,13.6,19.6,15.2,14.5,15.6,13.9,16.6,14.8,18.4,21,12.7,14.5,13.2,13.1,13.5,18.9,20,21,24.7,30.8,34.9]

#Variaveis preditoras
x1 = [0.00632, 0.02731, 0.02729, 0.03237, 0.06905, 0.02985, 0.08829, 0.14455, 0.21124, 0.17004, 0.22489, 0.11747, 0.09378, 0.62976, 0.63796, 0.62739, 105.393, 0.7842, 0.80271, 0.7258, 125.179, 0.85204, 123.247, 0.98843, 0.75026, 0.84054, 0.67191, 0.95577, 0.77299, 100.245, 113.081, 135.472, 138.799, 115.172, 161.282, 0.06417, 0.09744, 0.08014, 0.17505, 0.02763, 0.03359]

x2 = [18,0,0,0,0,0,12.5,12.5,12.5,12.5,12.5,12.5,12.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,75]

x3 = [2.310,7.070,7.070,2.180,2.180,2.180,7.870,7.870,7.870,7.870,7.870,7.870,7.870,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,8.140,5.960,5.960,5.960,5.960,2.950,2.950]


x4 = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

x5 = [0.538,0.469,0.469,0.458,0.458,0.458,0.524,0.524,0.524,0.524,0.524,0.524,0.524,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.538,0.499,0.499,0.499,0.499,0.428,0.428,]

x6 = [65.750,64.210,71.850,69.980,71.470,64.300,60.120,61.720,56.310,60.040,63.770,60.090,58.890,59.490,60.960,58.340,59.350,59.900,54.560,57.270,55.700,59.650,61.420,58.130,59.240,55.990,58.130,60.470,64.950,66.740,57.130,60.720,59.500,57.010,60.960,59.330,58.410,58.500,59.660,65.950,70.240]

x7 = [65.2,78.9,61.1,45.8,54.2,58.7,66.6,96.1,100,85.9,94.3,82.9,39,61.8,84.5,56.5,29.3,81.7,36.6,69.5,98.1,89.2,91.7,100,94.1,85.7,90.3,88.8,94.4,87.3,94.1,100,82,95,96.9,68.2,61.4,41.5,30.2,21.8,15.8]

x8 = [40.900,49.671,49.671,60.622,60.622,60.622,55.605,59.505,60.821,65.921,63.467,62.267,54.509,47.075,44.619,44.986,44.986,42.579,37.965,37.965,37.979,40.123,39.769,40.952,43.996,44.546,46.820,44.534,44.547,42.390,42.330,41.750,39.900,37.872,37.598,33.603,33.779,39.342,38.473,54.011,54.011]

x9 = [12,2,3,3,3,5,5,5,5,5,5,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,3,3]

x10 = [296,242,242,222,222,222,311,311,311,311,311,311,311,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,307,279,279,279,279,252,252]

x11 = [15.3,17.8,17.8,18.7,18.7,18.7,15.2,15.2,15.2,15.2,15.2,15.2,15.2,21,21,21,21,21,21,21,21,

21,21,21,21,21,21,21,21,21,21,21,21,21,21,19.2,19.2,19.2,19.2,18.3,18.3]

x12 = [396.9,396.9,392.83,394.63,396.9,394.12,395.6,396.9,386.63,386.71,392.52,396.9,390.5,396.9,380.02,395.62,386.85,386.75,288.99,390.95,376.57,392.53,396.9,394.54,394.33,303.42,376.88,306.38,387.94,380.23,360.17,376.73,232.6,358.77,248.31,396.9,377.56,396.9,393.43,395.63,395.62]

x13 = [4.98,9.14,4.03,2.94,5.33,5.21,12.43,19.15,29.93,17.1,20.45,13.27,15.71,8.26,10.26,8.47,6.58,14.67,11.69,11.28,21.02,13.83,18.72,19.88,16.3,16.51,14.81,17.28,12.8,11.98,22.6,13.04,27.71,18.35,20.34,9.68,11.41,8.77,10.13,4.32,1.98]



In [3]:
x = np.concatenate([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13])  #Agrupa as variaveis preditorass
np.array(x)

array([6.32000e-03, 2.73100e-02, 2.72900e-02, 3.23700e-02, 6.90500e-02,
       2.98500e-02, 8.82900e-02, 1.44550e-01, 2.11240e-01, 1.70040e-01,
       2.24890e-01, 1.17470e-01, 9.37800e-02, 6.29760e-01, 6.37960e-01,
       6.27390e-01, 1.05393e+02, 7.84200e-01, 8.02710e-01, 7.25800e-01,
       1.25179e+02, 8.52040e-01, 1.23247e+02, 9.88430e-01, 7.50260e-01,
       8.40540e-01, 6.71910e-01, 9.55770e-01, 7.72990e-01, 1.00245e+02,
       1.13081e+02, 1.35472e+02, 1.38799e+02, 1.15172e+02, 1.61282e+02,
       6.41700e-02, 9.74400e-02, 8.01400e-02, 1.75050e-01, 2.76300e-02,
       3.35900e-02, 1.80000e+01, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.25000e+01, 1.25000e+01, 1.25000e+01,
       1.25000e+01, 1.25000e+01, 1.25000e+01, 1.25000e+01, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.000

In [4]:
x = sm.add_constant(x, prepend=True) #Adiciona a coluna das constantes
x

array([[1.000e+00, 6.320e-03],
       [1.000e+00, 2.731e-02],
       [1.000e+00, 2.729e-02],
       ...,
       [1.000e+00, 1.013e+01],
       [1.000e+00, 4.320e+00],
       [1.000e+00, 1.980e+00]])

In [20]:
y = np.arange(532)
y

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [22]:
res = sm.OLS(y,x).fit() #Cria e ajusta o modelo

In [24]:
print(res.params)

[221.72763061   0.6130739 ]


In [25]:
print (res.bse)

[6.89610624 0.05017815]


In [27]:
print (res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.220
Model:                            OLS   Adj. R-squared:                  0.218
Method:                 Least Squares   F-statistic:                     149.3
Date:                Thu, 18 Feb 2021   Prob (F-statistic):           2.02e-30
Time:                        10:23:54   Log-Likelihood:                -3367.1
No. Observations:                 532   AIC:                             6738.
Df Residuals:                     530   BIC:                             6747.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        221.7276      6.896     32.153      0.0