# Regressão linear simples

In [ ]:
# Modelo teorico 
y = Bo + B1x + £  


Bo = intercepto
B1 = Inclinação
£ = Erro aleatório

In [2]:
# Exemplo em Python. Importação de bibliotecas

import numpy as np  # Importando biblioteca NumPy (Utilizado para cálculos múltidimensional)
import pandas as pd # Importando biblioteca Pandas (Utilizado para análises de dados)
from sklearn.linear_model import LinearRegression # Importando biblioteca utilizado biblioteca própria para regressão linear
import statsmodels.api as sm # Utilizado para modelos estátisticos 


In [5]:
# variável preditora
x = np.array([ 220, 220, 220, 220, 220, 225, 225, 225, 225, 225, 230, 230, 230, 230, 230, 235, 235, 235, 235, 235 ])

# variável alvo
y = np.array([ 137, 137, 137, 136, 135, 135, 133, 132, 133, 133, 128, 124, 126, 129, 126, 122, 122, 122, 119, 122 ])

print (x) 

print(y)

[220 220 220 220 220 225 225 225 225 225 230 230 230 230 230 235 235 235
 235 235]
[137 137 137 136 135 135 133 132 133 133 128 124 126 129 126 122 122 122
 119 122]


### VISUALIZANDO ESTÁTISTICAS DO MODELO USANDO statsmodels

In [25]:
# Adicionar uma constante a matriz X

X_sm = sm.add_constant(x)
X_sm

array([[  1., 220.],
       [  1., 220.],
       [  1., 220.],
       [  1., 220.],
       [  1., 220.],
       [  1., 225.],
       [  1., 225.],
       [  1., 225.],
       [  1., 225.],
       [  1., 225.],
       [  1., 230.],
       [  1., 230.],
       [  1., 230.],
       [  1., 230.],
       [  1., 230.],
       [  1., 235.],
       [  1., 235.],
       [  1., 235.],
       [  1., 235.],
       [  1., 235.]])

In [26]:
# OLS vem de Ordinary Least Squares (Mínimos Quadrados Ordinários) e o método fit irá treinar o modelo 
results = sm.OLS(y, X_sm).fit() # Utilizar para a regressão de resultados 

# Verificando as estatísticas do modelo
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.939
Method:                 Least Squares   F-statistic:                     291.1
Date:                Thu, 11 Feb 2021   Prob (F-statistic):           1.47e-12
Time:                        19:59:28   Log-Likelihood:                -35.596
No. Observations:                  20   AIC:                             75.19
Df Residuals:                      18   BIC:                             77.18
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        364.1800     13.765     26.457      0.000     335.261     393.099
x1            -1.0320      0.060    -17.062      0.000      -1.159      -0.905
==============================================================================
Omnibus:                        0.433   Durbin-Watson:                   2.235
Prob(Omnibus):                  0.805   Jarque-Bera (JB):                0.115
Skew:                          -0.182   Prob(JB):                        0.944
Kurtosis:                       2.926   Cond. No.                     9.26e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.26e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:
# Mostrar as previsões para o mesmo conjunto passado
results.predict(X_sm)

array([137.14, 137.14, 137.14, 137.14, 137.14, 131.98, 131.98, 131.98,
       131.98, 131.98, 126.82, 126.82, 126.82, 126.82, 126.82, 121.66,
       121.66, 121.66, 121.66, 121.66])

### Escrevendo o modelo com o scikit-lean

In [6]:
df = pd.DataFrame()
df['x'] = x
df['y'] = y
df

x    y
0   220  137
1   220  137
2   220  137
3   220  136
4   220  135
5   225  135
6   225  133
7   225  132
8   225  133
9   225  133
10  230  128
11  230  124
12  230  126
13  230  129
14  230  126
15  235  122
16  235  122
17  235  122
18  235  119
19  235  122

In [7]:
# Passando os valores de x e y como Dataframes
x_value = df[['x']] # Utiliza 2 conchetes por ser bidimensional
y_value = df[['y']]

In [8]:
# criando e treinando o modelo
model = LinearRegression() # Passando a função linear para a variável model
model.fit(x_value, y_value) # Transferindo as variáveis (x_value, y_value) para o método .fit de treinamento de aprendizagem 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
# Para visualizar os coeficientes encontrados
model.coef_

array([[-1.032]])

In [22]:
# Para visualizar o R²
model.score(x_value, y_value)

0.9417657045840407

In [42]:
# mostrando as previsões para o mesmo conjunto passado
model.predict(x_value)

array([[137.14],
       [137.14],
       [137.14],
       [137.14],
       [137.14],
       [131.98],
       [131.98],
       [131.98],
       [131.98],
       [131.98],
       [126.82],
       [126.82],
       [126.82],
       [126.82],
       [126.82],
       [121.66],
       [121.66],
       [121.66],
       [121.66],
       [121.66]])